# Generated by Django 4.0.6 on 2022-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_create', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employee_rfc', models.CharField(max_length=50)),
                ('employee_photo', models.ImageField(null=True, upload_to='Empleados/Oficinas')),
                ('employee_signature', models.ImageField(null=True, upload_to='Empleados/Oficinas')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTruck',
            fields=[
                ('employee_create', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employee_license', models.CharField(max_length=50)),
                ('employee_rfc', models.CharField(max_length=50)),
                ('employee_photo', models.ImageField(null=True, upload_to='Empleados/Operadores')),
                ('employee_signature', models.ImageField(null=True, upload_to='Empleados/Operadores')),
            ],
        ),
    ]
