# Generated by Django 4.0.6 on 2022-08-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetruck',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Empleados/Operadores'),
        ),
        migrations.AlterField(
            model_name='employeetruck',
            name='employee_signature',
            field=models.ImageField(blank=True, null=True, upload_to='Empleados/Operadores'),
        ),
    ]
