# Generated by Django 4.0.6 on 2022-08-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('trailer_created', models.DateTimeField(auto_now_add=True)),
                ('trailer_modified', models.DateTimeField(auto_now=True)),
                ('trailer_code', models.CharField(max_length=50)),
                ('trailer_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trailer_plate', models.CharField(max_length=50)),
                ('trailer_model', models.CharField(max_length=50)),
                ('trailer_serial', models.CharField(max_length=50)),
                ('trailer_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_created', models.DateTimeField(auto_now_add=True)),
                ('truck_modified', models.DateTimeField(auto_now=True)),
                ('truck_code', models.CharField(max_length=50)),
                ('truck_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_plates', models.CharField(max_length=50)),
                ('truck_serial', models.CharField(max_length=50)),
                ('truck_engine', models.CharField(max_length=50)),
                ('truck_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employeetruck')),
            ],
        ),
    ]
