# Generated by Django 4.0.6 on 2022-08-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleetvehicle', '0001_initial'),
        ('inspectionsvehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('access_control', models.CharField(choices=[('Entrada de Unidad', 'Entrada de Unidad'), ('Salida de Unidad', 'Salida de Unidad')], max_length=50)),
                ('access_inspection_completed', models.BooleanField(null=True)),
                ('access_inspection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspectionsvehicle.inspection')),
                ('access_trailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleetvehicle.trailer')),
                ('access_truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleetvehicle.truck')),
            ],
        ),
    ]
