# Generated by Django 4.0.6 on 2022-08-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionsvehicle', '0002_alter_inspection_inspection_box_backdoors_and_more'),
        ('fleetvehicle', '0002_alter_truck_truck_driver'),
        ('accessvehicle', '0002_alter_accessvehicle_access_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_control',
            field=models.CharField(blank=True, choices=[('Entrada de Unidad', 'Entrada de Unidad'), ('Salida de Unidad', 'Salida de Unidad')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspectionsvehicle.inspection'),
        ),
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_inspection_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleetvehicle.trailer'),
        ),
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleetvehicle.truck'),
        ),
    ]
