# Generated by Django 4.0.6 on 2022-08-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetvehicle', '0002_alter_truck_truck_driver'),
        ('accessvehicle', '0003_alter_accessvehicle_access_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_control',
            field=models.CharField(choices=[('Entrada de Unidad', 'Entrada de Unidad'), ('Salida de Unidad', 'Salida de Unidad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleetvehicle.trailer'),
        ),
        migrations.AlterField(
            model_name='accessvehicle',
            name='access_truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleetvehicle.truck'),
        ),
    ]
