# Generated by Django 4.2 on 2023-04-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessvehicle', '0004_alter_accessvehicle_access_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessvehicle',
            name='access_inspection_completed',
        ),
    ]
