# Generated by Django 4.0.6 on 2022-08-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleetvehicle', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_create', models.DateTimeField(auto_now=True)),
                ('inspection_carrier', models.CharField(choices=[('Transportes Refrigerados Rivas', 'Transportes Refrigerados Rivas')], max_length=100)),
                ('inspection_truck_defense', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_truck_defense_image', models.ImageField(upload_to='Inspecciones/Tractocamiones')),
                ('inspection_truck_engine', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_truck_engine_image', models.ImageField(upload_to='Inspecciones/Tractocamiones')),
                ('inspection_truck_fueltank', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_truck_fueltank_image', models.ImageField(upload_to='Inspecciones/Tractocamiones')),
                ('inspection_truck_tires', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_truck_tires_image', models.ImageField(upload_to='Inspecciones/Tractocamiones')),
                ('inspection_box_coolingunit', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_box_coolingunit_image', models.ImageField(upload_to='Inspecciones/Cajas')),
                ('inspection_box_leftwall', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_box_leftwall_image', models.ImageField(upload_to='Inspecciones/Cajas')),
                ('inspection_box_rightwall', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_box_rightwall_image', models.ImageField(upload_to='Inspecciones/Cajas')),
                ('inspection_box_backdoors', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_box_backdoors_image', models.ImageField(upload_to='Inspecciones/Cajas')),
                ('inspection_box_under', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_box_under_image', models.ImageField(upload_to='Inspecciones/Cajas')),
                ('inspection_box_tires', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_box_tires_image', models.ImageField(upload_to='Inspecciones/Cajas')),
                ('inspection_box_seal', models.CharField(max_length=100)),
                ('inspection_box_seal_image', models.ImageField(upload_to='Inspecciones/Cajas')),
                ('inspection_box_pollutants', models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100)),
                ('inspection_document_departamentmotors', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=100)),
                ('inspection_document_invoice', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=100)),
                ('inspection_document_circulation', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=100)),
                ('inspection_document_physicalmechanics', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=100)),
                ('inspection_document_securepolicy', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=100)),
                ('inspection_box_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleetvehicle.trailer')),
                ('inspection_inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('inspection_truck_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetvehicle.truck')),
            ],
        ),
    ]
