# Generated by Django 4.0.6 on 2022-08-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionsvehicle', '0003_inspection_inspection_box_airduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_box_airduct',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_box_backdoors_inside',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_box_backdoors_inside_image',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_box_floor',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_box_load',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_box_walls_inside',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_box_walls_inside_image',
        ),
    ]
