# Generated by Django 4.0.6 on 2022-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionsvehicle', '0004_remove_inspection_inspection_box_airduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_airduct',
            field=models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_backdoors_inside',
            field=models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_backdoors_inside_image',
            field=models.ImageField(null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_floor',
            field=models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_load',
            field=models.CharField(choices=[('Con carga', 'Con carga'), ('Sin carga', 'Sin carga')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_walls_inside',
            field=models.CharField(choices=[('Con anomalías', 'Con anomalías'), ('Sin anomalías', 'Sin anomalías')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_walls_inside_image',
            field=models.ImageField(null=True, upload_to='Inspecciones/Cajas'),
        ),
    ]
