# Generated by Django 4.0.6 on 2022-12-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionsvehicle', '0005_inspection_inspection_box_airduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_box_pollutants_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_backdoors_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_backdoors_inside_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_coolingunit_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_leftwall_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_rightwall_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_seal_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_tires_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_under_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_box_walls_inside_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Cajas'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_truck_defense_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Tractocamiones'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_truck_engine_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Tractocamiones'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_truck_fueltank_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Tractocamiones'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_truck_tires_image',
            field=models.ImageField(blank=True, null=True, upload_to='Inspecciones/Tractocamiones'),
        ),
    ]
