# Generated by Django 4.0.6 on 2023-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionsvehicle', '0006_inspection_inspection_box_pollutants_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_document_cp',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_document_cp_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
