# Generated by Django 4.0.6 on 2023-02-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionsvehicle', '0007_inspection_inspection_document_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_document_cp',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_document_cp_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
